minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - '@types/node@24.13.5'

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 144000
shellEmulator: true

allowBuilds:
  esbuild: true
  sharp: false
  simple-git-hooks: true
  unrs-resolver: false
  vue-demi: true
